services:
  backend:
    build:
      context: ./mern/backend
      dockerfile: dockerfile
    container_name: backend-con
    ports:
      - "5050:5050"
    networks:
      - mern-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongodb
  
  frontend:
    build:
      context: ./mern/frontend
      dockerfile: dockerfile
    container_name: frontend-con
    ports:
      - "5173:5173"
    networks:
      - mern-network
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5050

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
