version: '3'

services:

  apache:
    build:
      context: ./apache
      dockerfile: dockerfile
    image: apache-image
    ports:
      - 8081:80
    volumes:
      - apache_volume:/apps
    networks:
      - com-over

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    image: nginx-image
    ports:
      - 8082-8083:80
    volumes:
      - nginx_volume:/apps
    networks:
      - com-over

volumes:
  apache_volume:
  nginx_volume:

networks:
  com-over:
    driver: bridge
