FROM ubuntu:latest

RUN apt-get update && apt-get install apache2 -y && apt-get install nano -y

WORKDIR /var/www/html/

COPY index.html /var/www/html/

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
