version: '3'

services:
  wordpress:
    depends_on:
      - db
    image: wordpress:4.9.4-php7.2-apache
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8000-8001:80
    restart: always
    volumes:
      - wp_volume:/var/www/html
    networks:
      - brinet

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    restart: always
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - brinet

volumes:
  wp_volume:
  db_volume:

networks:
  brinet:
    driver: bridge

